name: Android CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Run all unit tests
      run: ./gradlew test --stacktrace
      working-directory: ./
    
    - name: Upload unit test results to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: unit-tests-results
        path: app/build/reports/tests/testDebugUnitTest/index.html
 
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build the project
      run: ./gradlew build --stacktrace
      working-directory: ./
      
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Generate APK
      run: ./gradlew assembleRelease --stacktrace
      working-directory: ./
      
    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
    # ID used to access action output
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      
    # Example use of `signedReleaseFile` output -- not needed
    - uses: actions/upload-artifact@v2
      with:
        name: Upload APK
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
      
   # - name: Upload APK to artifacts
    #  uses: actions/upload-artifact@v1
     # with:
      #  name: app
       # path: app/build/outputs/apk/release/app-release.apk
